INSERT INTO person (name, age, email) VALUES ('Tom', 25, 'tom@mail.ru');
INSERT INTO person (name, age, email) VALUES ('Kot', 35, 'kot@mail.ru');
INSERT INTO person (name, age, email) VALUES ('Tim', 27, 'tim@mail.ru');
INSERT INTO person (name, age, email) VALUES ('Nik', 19, 'tnik@mail.ru');

CREATE TABLE Item(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    person_id int REFERENCES person(id) on DELETE SET NULL ,
    item_name varchar(100) NOT NULL
);

INSERT INTO Item (person_id, item_name) VALUES (5,'Airpods');
INSERT INTO Item (person_id, item_name) VALUES (5,'Playstation');
INSERT INTO Item (person_id, item_name) VALUES (5,'TV');
