INSERT INTO person (name, age, email)
VALUES ('Tom', 25, 'tom@mail.ru');
INSERT INTO person (name, age, email)
VALUES ('Kot', 35, 'kot@mail.ru');
INSERT INTO person (name, age, email)
VALUES ('Tim', 27, 'tim@mail.ru');
INSERT INTO person (name, age, email)
VALUES ('Nik', 19, 'tnik@mail.ru');

CREATE TABLE Item
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT          REFERENCES person (id) ON DELETE SET NULL,
    item_name VARCHAR(100) NOT NULL
);

INSERT INTO Item (person_id, item_name)
VALUES (5, 'Airpods');
INSERT INTO Item (person_id, item_name)
VALUES (5, 'Playstation');
INSERT INTO Item (person_id, item_name)
VALUES (5, 'TV');

-- Добавим:
-- Просто дата без точного времени
ALTER TABLE person
    ADD COLUMN date_of_birth DATE;

-- Точное время
-- Значения timestamp сохраняются в секундах до или после полуночи 1 января 2000 г.
ALTER TABLE person
    ADD COLUMN created_at TIMESTAMP;

ALTER TABLE person
    ADD COLUMN mood INT;
-- так как выбрали Ordinal

ALTER TABLE person DROP COLUMN mood;
ALTER TABLE person ADD COLUMN mood varchar;